export const ogIcons = {
	archive: chrome.runtime.getURL('icons/old/low res/archive-24.png'),
	audio: chrome.runtime.getURL('icons/old/low res/audio-24.png'),
	avi: chrome.runtime.getURL('icons/old/low res/avi-24.png'),
	bmp: chrome.runtime.getURL('icons/old/low res/bmp-24.png'),
	calc: chrome.runtime.getURL('icons/old/low res/calc-24.png'),
	document: chrome.runtime.getURL('icons/old/low res/document-24.png'),
	flash: chrome.runtime.getURL('icons/old/low res/flash-24.png'),
	folder: chrome.runtime.getURL('icons/old/low res/folder-24.png'),
	gif: chrome.runtime.getURL('icons/old/low res/gif-24.png'),
	glossary: chrome.runtime.getURL('icons/old/low res/res/glossary.png'),
	image: chrome.runtime.getURL('icons/old/low res/image-24.png'),
	impress: chrome.runtime.getURL('icons/old/low res/impress-24.png'),
	jpeg: chrome.runtime.getURL('icons/old/low res/jpeg-24.png'),
	mp3: chrome.runtime.getURL('icons/old/low res/mp3-24.png'),
	mpeg: chrome.runtime.getURL('icons/old/low res/mpeg-24.png'),
	pdf: chrome.runtime.getURL('icons/old/low res/pdf-24.png'),
	png: chrome.runtime.getURL('icons/old/low res/png-24.png'),
	powerpoint: chrome.runtime.getURL('icons/old/low res/powerpoint-24.png'),
	quicktime: chrome.runtime.getURL('icons/old/low res/quicktime-24.png'),
	sourcecode: chrome.runtime.getURL('icons/old/low res/sourcecode-24.png'),
	spreadsheet: chrome.runtime.getURL('icons/old/low res/spreadsheet-24.png'),
	text: chrome.runtime.getURL('icons/old/low res/text-24.png'),
	tiff: chrome.runtime.getURL('icons/old/low res/tiff-24.png'),
	unknown: chrome.runtime.getURL('icons/old/low res/unknown-24.png'),
	video: chrome.runtime.getURL('icons/old/low res/video-24.png'),
	wmv: chrome.runtime.getURL('icons/old/low res/wmv-24.png'),
	writer: chrome.runtime.getURL('icons/old/low res/writer-24.png'),
}

// If you find the original icons for any of the icons below, please let me know!
export const icons = {
	assignment: chrome.runtime.getURL('icons/custom/assignment.png'),
	forum: chrome.runtime.getURL('icons/custom/forum.png'),
	link: chrome.runtime.getURL('icons/custom/link.png'),
	page: chrome.runtime.getURL('icons/custom/page.png'),
	recording: chrome.runtime.getURL('icons/custom/recording.png'),
	// SCORM is the name of the לומדה provider company
	scorm: chrome.runtime.getURL('icons/custom/SCORM Interactive.png'),
}
