export const ogIcons = {
	archive: browser.runtime.getURL('icons/old/low res/archive-24.png'),
	audio: browser.runtime.getURL('icons/old/low res/audio-24.png'),
	avi: browser.runtime.getURL('icons/old/low res/avi-24.png'),
	bmp: browser.runtime.getURL('icons/old/low res/bmp-24.png'),
	calc: browser.runtime.getURL('icons/old/low res/calc-24.png'),
	document: browser.runtime.getURL('icons/old/low res/document-24.png'),
	flash: browser.runtime.getURL('icons/old/low res/flash-24.png'),
	folder: browser.runtime.getURL('icons/old/low res/folder-24.png'),
	gif: browser.runtime.getURL('icons/old/low res/gif-24.png'),
	glossary: browser.runtime.getURL('icons/old/low res/res/glossary.png'),
	image: browser.runtime.getURL('icons/old/low res/image-24.png'),
	impress: browser.runtime.getURL('icons/old/low res/impress-24.png'),
	jpeg: browser.runtime.getURL('icons/old/low res/jpeg-24.png'),
	mp3: browser.runtime.getURL('icons/old/low res/mp3-24.png'),
	mpeg: browser.runtime.getURL('icons/old/low res/mpeg-24.png'),
	pdf: browser.runtime.getURL('icons/old/low res/pdf-24.png'),
	png: browser.runtime.getURL('icons/old/low res/png-24.png'),
	powerpoint: browser.runtime.getURL('icons/old/low res/powerpoint-24.png'),
	quicktime: browser.runtime.getURL('icons/old/low res/quicktime-24.png'),
	sourcecode: browser.runtime.getURL('icons/old/low res/sourcecode-24.png'),
	spreadsheet: browser.runtime.getURL('icons/old/low res/spreadsheet-24.png'),
	text: browser.runtime.getURL('icons/old/low res/text-24.png'),
	tiff: browser.runtime.getURL('icons/old/low res/tiff-24.png'),
	unknown: browser.runtime.getURL('icons/old/low res/unknown-24.png'),
	video: browser.runtime.getURL('icons/old/low res/video-24.png'),
	wmv: browser.runtime.getURL('icons/old/low res/wmv-24.png'),
	writer: browser.runtime.getURL('icons/old/low res/writer-24.png'),
}

// If you find the original icons for any of the icons below, please let me know!
export const icons = {
	assignment: browser.runtime.getURL('icons/custom/assignment.png'),
	forum: browser.runtime.getURL('icons/custom/forum.png'),
	link: browser.runtime.getURL('icons/custom/link.png'),
	page: browser.runtime.getURL('icons/custom/page.png'),
	recording: browser.runtime.getURL('icons/custom/recording.png'),
	// SCORM is the name of the לומדה provider company
	scorm: browser.runtime.getURL('icons/custom/SCORM Interactive.png'),
}
